# Training configs for Seg

dataset : rice Dataset
n_classes : 2
channels : 21
ignore_index : 255
net : Attention_UNet
optimizer : adam
scheduler : StepLR
lr : 0.001
batchsize : 10
start_epoch : 0
end_epoch : 100
result_dir : "C:/Users/ADMIN/Desktop/S1L8/result/attention U-Net-adam/attunet-ADAM-0.001"
criterion : weight_crossentropy
logIterval : 10
valIterval : 2
resume : 
  flag : False
  state_path : "E:/PROGRAM/HZY/X_RESULT/1AttUNet_adam_0.001_10_BM/Attention_UNet-0.8668-ep15.pth"