# Training configs for Seg

dataset : rice Dataset
n_classes : 2
channels : 21
ignore_index : 255
net : UNet
optimizer : adam
scheduler : StepLR
lr : 0.001
batchsize : 10
start_epoch : 0
end_epoch : 100
result_dir : "C:/Users/ADMIN/Desktop/WML/S1L8/result/2024l8unet"
criterion : CrossEntropy #weight_crossentropy
logIterval : 10
valIterval : 2
resume :
  flag : False
  state_path : "./eventfiles-UNet-channels7/UNet-ep.pth"