# Training configs for Seg

dataset : Oil Dataset
channels : 21
n_classes : 2
ignore_index : 255
net : DeepLab
optimizer : adam
scheduler : StepLR
lr : 0.0001
batchsize : 8
start_epoch : 0
end_epoch : 100
result_dir : "./TransUnetTest/0612ventfiles-deeplab-channels4-SGD-bs=2-lI=20-lr=0.0001-ep=100"
criterion : crossentropy
logIterval : 20
valIterval : 2
resume :
  flag : True
  state_path : "D:/NET1/All_Net_GN/Net/Aeventfiles-deeplab-channels7-Adam-bs=8-lI=20-lr=0.0001-ep=100/DeepLab-0.9397-ep25.pth"
